### PR TITLE
Upstream merge

### PR DESCRIPTION
**Pull request by juliazero**
I resolved repo incompatibility ~~and translated two items in -base~~

### CODE REVIEW

**Comment by SpacingBat3** [comment]
Looks OK. I don't see any new strings translated though, I've only noticed some strings to be actually moved to `-base` from the previous location.

**Comment by SpacingBat3** [comment]
Also thx for helping me with keeping this repo fresh! I've also translated new `-vending` strings. I've also noticed microG is setting up localization via https://www.transifex.com/, or at least that's what newly added config suggests.

**Comment by juliazero** [comment]
> Looks OK. I don't see any new strings translated though, I've only noticed some strings to be actually moved to `-base` from the previous location.

Ah sorry, I translated them while resolving conflicts and this is why they hard to find :D
https://github.com/microg/GmsCore/blob/753fbd6c0aadfec1ce1a1f4b8e46fea6a297787b/play-services-base/core/src/main/res/values-pl/strings.xml#L23C7-L23C7
They were `On` and `Off` in `play-services-core/src/main/res/values/strings.xml`. Perhaps I should do it later as a separate commit.

> Also thx for helping me with keeping this repo fresh! I've also translated new `-vending` strings. I've also noticed microG is setting up localization via https://www.transifex.com/, or at least that's what newly added config suggests.

At this moment, the configuration file has been deleted, so it's hard to tell 😃

**Comment by SpacingBat3** [comment]
> Ah sorry, I translated them while resolving conflicts and this is why they hard to find :D [microg/GmsCore@`753fbd6`/play-services-base/core/src/main/res/values-pl/strings.xml#L23C7-L23C7](https://github.com/microg/GmsCore/blob/753fbd6c0aadfec1ce1a1f4b8e46fea6a297787b/play-services-base/core/src/main/res/values-pl/strings.xml#L23C7-L23C7) They were `On` and `Off` in `play-services-core/src/main/res/values/strings.xml`. Perhaps I should do it later as a separate commit.

Wasn't that defined in `play-services-core` previously? The diff seems to tell this was done before (+ I remember myself localizing that before):
https://github.com/SpacingBat3/GmsCore/pull/1/files#diff-41fd28704cd51671fd8c58dbd62544ba4f5fc22f0987b8b0009917bf623adcf8L51-L57

Outside of this, I haven't noticed any changes to localizations done, so I guess this PR indeed only resolved the conflicts. But still there were some leftovers left and I'm not sure if there are any additional items added in existing locales after you merged the upstream.

**Comment by juliazero** [comment]
Hmm... It seems that was something strange happened on my vscode and I had to add these two lines manually, I took them from `-base .../values/strings.xml`, I was wondering whether to translate them as `Wł` `Wył` or `Wł.` `Wył.` I selected second variant, then I pushed out changes and made this PR :D

According to the commit history this translation was already there, so in that case that's why my changes are not visible, because they are identical, so you are correct, this is only upstream merge, nothing else 😂

**Pull request merged**
